apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend
              key: redis-master
        - name: REDIS_SLAVE_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend
              key: redis-slave
        ports:
        - containerPort: 80
---
apiVersion: v1
data:
  master: redis-master
  slave: redis-slave
kind: ConfigMap
metadata:
  name: frontend
  namespace: default
